/**
 * Admin API: Regenerate OAuth Client Secret
 * 
 * POST /api/admin/oauth-clients/[clientId]/regenerate-secret - Generate new client secret
 * 
 * WHAT: Generates a new client secret and invalidates the old one
 * WHY: Needed when secret is compromised, lost, or needs rotation
 * HOW: Calls regenerateClientSecret() which generates UUID, hashes it, updates DB
 * 
 * Authentication: Requires valid admin session
 * Authorization: admin role required
 * 
 * Security:
 * - Old secret becomes invalid immediately
 * - New secret shown only once in response
 * - Existing refresh tokens remain valid (only token endpoint affected)
 */

import { requireUnifiedAdmin } from '../../../../../lib/auth.mjs'
import { regenerateClientSecret } from '../../../../../lib/oauth/clients.mjs'
import logger from '../../../../../lib/logger.mjs'
import { runCors } from '../../../../../lib/cors.mjs'

export default async function handler(req, res) {
  // Apply CORS
  if (runCors(req, res)) return

  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST')
    return res.status(405).json({ error: 'Method not allowed' })
  }

  // Authenticate admin user
  const adminUser = await requireUnifiedAdmin(req, res)


  // Require admin role
  if (adminUser.role !== 'admin') {
    logger.warn('OAuth client secret regeneration denied: insufficient permissions', {
      adminId: adminUser.id,
      role: adminUser.role,
    })
    return res.status(403).json({ error: 'Forbidden: admin role required' })
  }

  const { clientId } = req.query

  if (!clientId) {
    return res.status(400).json({ error: 'Client ID is required' })
  }

  try {
    // WHAT: Regenerate the client secret
    // WHY: Admin requested new secret (lost or compromised)
    const { client, client_secret } = await regenerateClientSecret(clientId)

    logger.warn('OAuth client secret regenerated by admin', {
      adminId: adminUser.id,
      adminEmail: adminUser.email,
      clientId,
      clientName: client.name,
    })

    // WHAT: Return new secret (only time it will be shown)
    return res.status(200).json({
      success: true,
      message: 'Client secret regenerated successfully. Save it now - it will not be shown again.',
      client,
      client_secret, // Plaintext secret - ONLY TIME IT'S EXPOSED
    })
  } catch (error) {
    logger.error('Failed to regenerate client secret', {
      error: error.message,
      adminId: adminUser.id,
      clientId,
    })

    return res.status(500).json({
      error: 'Internal server error',
      message: error.message,
    })
  }
}
